name: test_2_workflow
on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - main

jobs:
  order-books-spread:
    runs-on: ubuntu-latest
    name: Order_books Bitso API Connector
    steps:
    - uses: actions/checkout@v3
    - name: Deploy Bitso API Container
      uses: ./.github/actions/connector
      env:
        PYTHON_SCRIPT: "test_2.py"
        BITSO_API_URL_BTC_MXN: ${{ secrets.BITSO_API_URL_BTC_MXN }}
        BITSO_API_URL_USD_MXN: ${{ secrets.BITSO_API_URL_USD_MXN }}
        GH_USER_NAME: ${{ secrets.GH_USER_NAME }}
        GH_USER_EMAIL: ${{ secrets.GH_USER_EMAIL }}
