name: test_2_workflow
on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
      - testing-github-actions

jobs:
  order-books-spread:
    runs-on: ubuntu-latest
    name: Order_books Bitso API Connector
    steps:
    - uses: actions/checkout@v3
    - name: Test_1
      run: pwd
    - name: Deploy Bitso API Container
      uses: ./.github/actions/connector
      env:
        PYTHON_SCRIPT: "test_2.py"
        BITSO_API_URL_BTC_MXN: ${{ secrets.BITSO_API_URL_BTC_MXN }}
        BITSO_API_URL_USD_MXN: ${{ secrets.BITSO_API_URL_USD_MXN }}
    # - uses: actions/upload-artifact@master
    #   with:
    #     name: gh-artifact
    #     path: path/to/artifact
    # - name: Commit and Push new partitions into the data lake
    # - run: |
    #     git config --global user.name ${{ secrets.GH_USER_NAME }}
    #     git config --global user.email ${{ secrets.GH_USER_EMAIL }}
    #     git status
  spread-validation:
    needs: order-books-spread
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Commit and Push new partitions into the data lake
        run: |
          git config --global user.name ${{ secrets.GH_USER_NAME }}
          git config --global user.email ${{ secrets.GH_USER_EMAIL }}
          git commit -am "Added new partition"
          git push
