name: test_1_workflow
on:
  schedule:
    - cron: '0 11 * * *'
  push:
    branches:
      - main

jobs:
  coingecko-connector:
    runs-on: ubuntu-latest
    name: CoinGecko Connector
    steps:
    - uses: actions/checkout@v3
    - name: Deploy CoinGecko Container
      uses: ./.github/actions/coingecko_connector
