name: test_2_workflow
on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - main

jobs:
  order-books-spread:
    runs-on: ubuntu-latest
    name: Order_books Bitso API Connector
    steps:
    - uses: actions/checkout@v3
    - name: Deploy Bitso API Container
      uses: ./.github/actions/connector
      env:
        PYTHON_SCRIPT: "test_2.py"
        BITSO_API_URL_BTC_MXN: ${{ secrets.BITSO_API_URL_BTC_MXN }}
        BITSO_API_URL_USD_MXN: ${{ secrets.BITSO_API_URL_USD_MXN }}
    # - name: Commit and Push new partitions into the data lake
    - run: |
        git config --global user.name ${{ secrets.GH_USER_NAME }}
        git config --global user.email ${{ secrets.GH_USER_EMAIL }}
        git commit -am "Added new partition"
        git push
