name: test_1_workflow
on:
  schedule:
    - cron: '0 11 * * *'
  push:
    branches:
      - main

jobs:
  coingecko-connector:
    runs-on: ubuntu-latest
    name: CoinGecko Connector
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'    
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute py script
        run: python src/test_1.py
        - uses: actions/upload-artifact@v3
          with:
            name: gh-artifact
            path: /home/runner/work/bitso-test/bitso-test/data/test_1
  push-to-repo:
    needs: coingecko-connector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: gh-artifact
          path: /home/runner/work/bitso-test/bitso-test/data/test_1
      - name: Commit and Push tables into the repo
        run: |
          git config --global user.name ${{ secrets.GH_USER_NAME }}
          git config --global user.email ${{ secrets.GH_USER_EMAIL }}
          git add --all
          git commit -am "Added new data from CoinGecko"
          git push
      